name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up dotnet environment
      uses: actions/setup-dotnet@v2.1.0
      
    - name: list files
      run: ls
        
    - name: Attempt build
      run: dotnet build ClassChartsApi.sln
