name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up dotnet environment
      uses: xt0rted/setup-dotnet@v1.4.0
      with:
        dotnet-version: 6.0.0
        
    - name: Attempt build
      run: dotnet build
